version: 0.2

phases:
  install:
    commands:
      - yum install -y httpd || exit 1
  build:
    commands:
      - if grep -q "sami" index.html; then :; else exit 1; fi
  post_build:
    commands:
      - :
artifacts:
  files:
    - '**/*'
  discard-paths: no
